# Include shared CI
include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"


docker-run:
    # Define a 1D job matrix to inject a variable named MATRIX_NAME into
    #   the CI environment, we can use the value of MATRIX_NAME to determine
    #   which options to apply as part of the rules block below
    # NOTE There is a slightly cleaner way to define this matrix to include
    #   the variables, but it is broken when using long strings! See CW-756
    parallel:
        matrix:
            - MATRIX_NAME: [
                "single-file", "single-file-s3",
                "case01", "case01-s3",
                "case02", "case02-s3",
                "case03", "case03-s3",
                "case04", "case04-s3"]
    rules:
        # NOTE As we're overriding the rules block for the included docker-run
        #   we must redefine this CI_COMMIT_BRANCH rule to prevent docker-run
        #   being incorrectly scheduled for "detached merge request pipelines" etc.
        - if: ($CI_COMMIT_BRANCH == null || $CI_COMMIT_BRANCH == "dev-template")
          when: never
        - if: $MATRIX_NAME == "single-file"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/reads.fastq.gz"
        - if: $MATRIX_NAME == "single-file-s3"
          variables:
              NF_WORKFLOW_OPTS: "--fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-template/test_data/reads.fastq.gz"

        - if: $MATRIX_NAME == "case01"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq_ingress/case01"
        - if: $MATRIX_NAME == "case01-s3"
          variables:
              NF_WORKFLOW_OPTS: "--fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-template/test_data/fastq_ingress/case01"

        - if: $MATRIX_NAME == "case02"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq_ingress/case02"
        - if: $MATRIX_NAME == "case02-s3"
          variables:
              NF_WORKFLOW_OPTS: "--fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-template/test_data/fastq_ingress/case02"
        
        - if: $MATRIX_NAME == "case03"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq_ingress/case03"
        - if: $MATRIX_NAME == "case03-s3"
          variables:
              NF_WORKFLOW_OPTS: "--fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-template/test_data/fastq_ingress/case03"

        - if: $MATRIX_NAME == "case04"
          variables:
              NF_WORKFLOW_OPTS: "--fastq test_data/fastq_ingress/case04"
        - if: $MATRIX_NAME == "case04-s3"
          variables:
              NF_WORKFLOW_OPTS: "--fastq s3://ont-exd-int-s3-euwst1-epi2me-labs/wf-template/test_data/fastq_ingress/case04"
